"use client";
import { useEffect,useState } from "react";
import { browserApi } from "@/lib/browser-api";
import { MetricCard,PageHeader,money } from "@/components/UI";
type Latency={attempts:number;fill_rate:number|null;average_net_edge:number|null;average_pnl:number|null;win_rate:number|null};
type Summary={matches_observed:number;price_moves_recorded:number;dynamic_signals:number;paper_executions:number;median_poly_to_kalshi_lag_ms:number|null;median_kalshi_to_poly_lag_ms:number|null;lag_distribution:{polymarket_to_kalshi:number[];kalshi_to_polymarket:number[]};costs:{gross_pnl:number;fees:number;slippage:number;net_pnl:number};data_sufficient:boolean;test_data_excluded:boolean;latency:Record<string,Latency>;discovery?:{research_pairs:number;kalshi:{csl_like_markets:number};polymarket:{csl_like_markets:number}}};
export function CSLResearch(){const [s,setS]=useState<Summary|null>(null);useEffect(()=>{const load=()=>browserApi<Summary>("/csl/research/summary").then(setS).catch(()=>{});load();const t=setInterval(load,5000);return()=>clearInterval(t)},[]);return <><PageHeader eyebrow="CSL FORWARD TEST" title="研究" english="Research" description="中超跨平台 Lead/Lag、执行延迟与模拟结果。正式统计默认排除 is_test=true。"/><section className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="观察比赛" english="Matches Observed" value={s?.matches_observed||0}/><MetricCard label="价格记录" english="Price Moves Recorded" value={s?.price_moves_recorded||0}/><MetricCard label="动态信号" english="Dynamic Signals" value={s?.dynamic_signals||0}/><MetricCard label="模拟执行" english="Paper Executions" value={s?.paper_executions||0}/></section><section className="mb-6 grid gap-4 sm:grid-cols-2"><MetricCard label="Poly → Kalshi 中位滞后" english="Median Lag" value={s?.median_poly_to_kalshi_lag_ms==null?"Insufficient data":`${s.median_poly_to_kalshi_lag_ms.toFixed(0)} ms`}/><MetricCard label="Kalshi → Poly 中位滞后" english="Median Lag" value={s?.median_kalshi_to_poly_lag_ms==null?"Insufficient data":`${s.median_kalshi_to_poly_lag_ms.toFixed(0)} ms`}/></section><section className="card mb-6 p-6"><h2 className="mt-0">Edge vs Execution Latency</h2>{s?.data_sufficient?<LatencyTable latency={s.latency}/>:<div className="py-12 text-center"><h3>真实数据不足 Insufficient live data</h3><p className="text-sm text-zinc-500">没有动态信号和执行记录时，不显示模拟图表或漂亮收益。</p></div>}</section><section className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="毛收益" english="Gross PnL" value={money(s?.costs.gross_pnl||0)}/><MetricCard label="手续费" english="Fees" value={money(s?.costs.fees||0)}/><MetricCard label="滑点" english="Slippage" value={money(s?.costs.slippage||0)}/><MetricCard label="净收益" english="Net PnL" value={money(s?.costs.net_pnl||0)}/></section><section className="grid gap-5 lg:grid-cols-2"><div className="card p-6"><h2 className="mt-0">Lead/Lag Distribution</h2>{s&&(s.lag_distribution.polymarket_to_kalshi.length+s.lag_distribution.kalshi_to_polymarket.length)>0?<LagBars data={s.lag_distribution}/>:<p className="text-sm text-zinc-500">Insufficient live data for Poly → Kalshi or Kalshi → Poly latency distributions.</p>}</div><div className="card p-6"><h2 className="mt-0">策略隔离 Strategy Isolation</h2><p className="text-sm leading-6 text-zinc-500">Dynamic Lead/Lag 与 Static Arbitrage 分开统计。测试数据已排除：{s?.test_data_excluded?"YES":"—"}。</p></div></section></>}
function LatencyTable({latency}:{latency:Record<string,Latency>}){return <div className="overflow-x-auto"><table><thead><tr><th>Latency</th><th>Attempts</th><th>Fill Rate</th><th>Average Net Edge</th><th>Average PnL</th><th>Win Rate</th></tr></thead><tbody>{Object.entries(latency).map(([ms,x])=><tr key={ms}><td>{+ms>=1000?`${+ms/1000}s`:`${ms}ms`}</td><td>{x.attempts}</td><td>{x.fill_rate==null?"—":`${(x.fill_rate*100).toFixed(1)}%`}</td><td>{x.average_net_edge==null?"—":`${(x.average_net_edge*100).toFixed(2)}¢`}</td><td>{x.average_pnl==null?"—":money(x.average_pnl)}</td><td>{x.win_rate==null?"—":`${(x.win_rate*100).toFixed(1)}%`}</td></tr>)}</tbody></table></div>}
function LagBars({data}:{data:Summary["lag_distribution"]}){const rows=[["Poly → Kalshi",data.polymarket_to_kalshi],["Kalshi → Poly",data.kalshi_to_polymarket]] as const;const max=Math.max(1,...rows.flatMap(x=>x[1]));return <div className="space-y-5">{rows.map(([name,values])=><div key={name}><div className="mb-2 flex justify-between text-xs"><b>{name}</b><span>{values.length} observations</span></div><div className="flex h-24 items-end gap-1 rounded-xl bg-zinc-50 p-3">{values.slice(-40).map((v,i)=><div key={i} title={`${v.toFixed(0)}ms`} className="min-w-1 flex-1 rounded-t bg-zinc-500" style={{height:`${Math.max(5,v/max*100)}%`}}/>)}</div></div>)}</div>}
