"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Activity, BarChart3, Bug, LayoutDashboard, Settings } from "lucide-react";
import type { LucideIcon } from "lucide-react";
type NavItem=readonly [string,string,string,LucideIcon];
const primary=[['概览','Overview','/',LayoutDashboard],['实时比赛','Live Match','/live-match',Activity],['研究','Research','/research',BarChart3],['调试','Debug','/debug',Bug],['设置','Settings','/settings',Settings]] as const;
const secondary=[] as const;
export function Nav(){const path=usePathname();const render=(items:readonly NavItem[],quiet=false)=>items.map(([zh,en,href,Icon])=>{const active=href==='/'?path===href:path.startsWith(href);return <Link key={href} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 transition ${active?'bg-black text-white shadow-sm':quiet?'text-zinc-400 hover:bg-black/[.035] hover:text-zinc-700':'text-zinc-500 hover:bg-black/[.04] hover:text-zinc-900'}`}><Icon size={17}/><span><span className="block text-sm font-medium">{zh}</span><span className="block text-[10px] opacity-55">{en}</span></span></Link>});return <><aside className="desktop-nav fixed left-0 top-0 z-20 flex h-screen w-[230px] flex-col border-r border-black/[.055] bg-white/75 px-5 py-7 backdrop-blur-xl"><Link href="/" className="mb-9 flex items-center gap-3 px-2"><span className="grid h-9 w-9 place-items-center rounded-xl bg-black text-sm font-bold text-white">A</span><span className="text-lg font-semibold tracking-tight">ArbiCast</span></Link><nav className="space-y-1">{render(primary)}</nav><nav className="mt-5 space-y-1 border-t border-zinc-100 pt-4">{render(secondary,true)}</nav><div className="mt-auto rounded-2xl bg-zinc-100 p-4"><div className="mb-1 text-xs font-semibold">研究模式 Research Mode</div><p className="m-0 text-[11px] leading-4 text-zinc-500">只读市场数据与模拟交易。真实下单永久禁用。</p></div></aside><header className="sticky top-0 z-20 flex items-center justify-between border-b border-black/5 bg-white/80 px-5 py-3 backdrop-blur-xl md:hidden"><Link href="/" className="font-semibold">ArbiCast</Link><span className="pill bg-zinc-100 text-zinc-600">研究 Research</span></header></>}
