import { AlertTriangle, ArrowUpRight, CircleHelp } from "lucide-react";
import Link from "next/link";
import type { Opportunity } from "@/lib/types";
export const money=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v);
export const pct=(v:number)=>`${(v*100).toFixed(2)}%`;
export function PageHeader({eyebrow,title,english,description}:{eyebrow?:string;title:string;english?:string;description?:string}){return <div className="mb-8">{eyebrow&&<div className="mb-2 text-xs font-semibold uppercase tracking-[.16em] text-zinc-400">{eyebrow}</div>}<h1 className="m-0 text-4xl font-semibold tracking-[-.045em] md:text-5xl">{title}</h1>{english&&<div className="mt-1 text-sm font-semibold uppercase tracking-[.14em] text-zinc-400">{english}</div>}{description&&<p className="mt-3 max-w-2xl whitespace-pre-line text-[15px] leading-6 text-zinc-500">{description}</p>}</div>}
export function BiLabel({zh,en,className=""}:{zh:string;en:string;className?:string}){return <span className={className}><span className="block">{zh}</span><span className="mt-0.5 block text-[10px] font-medium uppercase tracking-[.08em] opacity-55">{en}</span></span>}
export function MetricCard({label,english,value,detail,tone,tooltip}:{label:string;english?:string;value:string|number;detail?:string;tone?:'positive';tooltip?:string}){return <div className="card p-5 md:p-6"><div className="label mb-4 flex items-start justify-between"><BiLabel zh={label} en={english||""}/>{tooltip&&<Tooltip text={tooltip}/>}</div><div className={`metric ${tone==='positive'?'positive':''}`}>{value}</div>{detail&&<div className="mt-2 text-xs text-zinc-400">{detail}</div>}</div>}
export function Tooltip({text}:{text:string}){return <span title={text} className="group relative ml-1 inline-flex cursor-help text-zinc-400"><CircleHelp size={14}/><span className="pointer-events-none absolute right-0 top-6 z-50 hidden w-64 whitespace-pre-line rounded-xl bg-zinc-900 p-3 text-left text-[11px] font-normal leading-5 text-white shadow-xl group-hover:block">{text}</span></span>}
export function Warning({children}:{children:React.ReactNode}){return <div className="flex gap-3 rounded-2xl bg-amber-50 p-4 text-sm leading-5 text-amber-900"><AlertTriangle className="mt-0.5 shrink-0" size={16}/><div>{children}</div></div>}
export function OpportunityCard({opportunity}:{opportunity:Opportunity}){const o=opportunity;return <article className="card p-6"><div className="flex items-start justify-between gap-4"><div><div className="mb-2 text-xs font-semibold uppercase tracking-wider text-zinc-400">{o.category}</div><h3 className="m-0 text-xl font-semibold tracking-tight">{o.event}</h3></div><span className="pill bg-emerald-50 text-emerald-700">实时 Live</span></div><div className="my-6 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-zinc-50 p-4"><div className="label">买入 Buy · Kalshi {o.kalshi_side}</div><div className="mt-1 text-2xl font-semibold">{(o.kalshi_price*100).toFixed(1)}¢</div></div><div className="rounded-2xl bg-zinc-50 p-4"><div className="label">买入 Buy · Polymarket {o.polymarket_side}</div><div className="mt-1 text-2xl font-semibold">{(o.polymarket_price*100).toFixed(1)}¢</div></div></div><div className="grid grid-cols-2 gap-5 border-y border-zinc-100 py-5 md:grid-cols-4"><Small label="总成本 Total Cost" value={`${((o.kalshi_price+o.polymarket_price)*100).toFixed(1)}¢`}/><Small label="净套利空间 Net Edge" value={pct(o.net_edge)} positive/><Small label="可成交金额 Available Size" value={money(o.available_size)}/><Small label="预计利润 Expected Profit" value={money(o.expected_profit)} positive/></div><details className="mt-4 rounded-xl bg-zinc-50 px-4 py-3 text-xs text-zinc-500"><summary className="cursor-pointer font-semibold text-zinc-700">高级详情 Advanced Details</summary><div className="mt-3 grid grid-cols-3 gap-3"><Small label="Gross Edge" value={pct(o.gross_edge)}/><Small label="Fees" value={pct(o.estimated_fees)}/><Small label="Duration" value={`${o.duration_seconds.toFixed(1)} sec`}/></div></details><Link href={`/opportunities/${o.id}`} className="mt-5 flex items-center justify-end gap-1 text-sm font-semibold text-zinc-700">查看详情 View details <ArrowUpRight size={15}/></Link></article>}
export function Small({label,value,positive}:{label:string;value:string;positive?:boolean}){return <div><div className="label mb-1">{label}</div><div className={`text-sm font-semibold ${positive?'positive':''}`}>{value}</div></div>}
