"""CSL match sessions, ticks, lead-lag signals and execution scenarios."""
from alembic import op
import sqlalchemy as sa

revision = "20260821_04"
down_revision = "20260820_03"
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("csl_match_sessions",sa.Column("id",sa.String(180),primary_key=True),sa.Column("league",sa.String(20),nullable=False),sa.Column("season",sa.String(20),nullable=False),sa.Column("home_team",sa.String(120),nullable=False),sa.Column("away_team",sa.String(120),nullable=False),sa.Column("scheduled_start",sa.DateTime(timezone=True),nullable=False),sa.Column("actual_start",sa.DateTime(timezone=True)),sa.Column("status",sa.String(24),nullable=False),sa.Column("match_minute",sa.Integer),sa.Column("match_second",sa.Integer),sa.Column("home_score",sa.Integer),sa.Column("away_score",sa.Integer),sa.Column("pair_id",sa.String(700)),sa.Column("markets",sa.JSON,nullable=False),sa.Column("metadata_json",sa.JSON,nullable=False),sa.Column("is_test",sa.Boolean,nullable=False,server_default=sa.false()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    for col in ("league","home_team","away_team","scheduled_start","status","pair_id","is_test"):op.create_index(f"ix_csl_match_sessions_{col}","csl_match_sessions",[col])
    op.create_table("csl_market_price_ticks",sa.Column("id",sa.Integer,primary_key=True),sa.Column("match_session_id",sa.String(180),nullable=False),sa.Column("venue",sa.String(20),nullable=False),sa.Column("market_id",sa.String(300),nullable=False),sa.Column("outcome",sa.String(12),nullable=False),sa.Column("exchange_timestamp",sa.DateTime(timezone=True)),sa.Column("received_timestamp",sa.DateTime(timezone=True),nullable=False),sa.Column("stored_timestamp",sa.DateTime(timezone=True),nullable=False),sa.Column("best_bid",sa.Float),sa.Column("best_ask",sa.Float),sa.Column("bid_size",sa.Float),sa.Column("ask_size",sa.Float),sa.Column("mid_price",sa.Float),sa.Column("vwap_5",sa.Float),sa.Column("vwap_25",sa.Float),sa.Column("vwap_100",sa.Float),sa.Column("book_sequence",sa.String(120)),sa.Column("payload",sa.JSON,nullable=False),sa.Column("is_test",sa.Boolean,nullable=False,server_default=sa.false()))
    for name,cols in (("ix_csl_ticks_session_time",["match_session_id","received_timestamp"]),("ix_csl_ticks_series",["match_session_id","venue","outcome","received_timestamp"]),("ix_csl_market_price_ticks_venue",["venue"]),("ix_csl_market_price_ticks_market_id",["market_id"]),("ix_csl_market_price_ticks_outcome",["outcome"]),("ix_csl_market_price_ticks_received_timestamp",["received_timestamp"]),("ix_csl_market_price_ticks_is_test",["is_test"])):op.create_index(name,"csl_market_price_ticks",cols)
    op.create_table("csl_dynamic_signals",sa.Column("id",sa.String(220),primary_key=True),sa.Column("match_session_id",sa.String(180),nullable=False),sa.Column("outcome",sa.String(12),nullable=False),sa.Column("strategy_type",sa.String(32),nullable=False),sa.Column("leader_venue",sa.String(20),nullable=False),sa.Column("follower_venue",sa.String(20),nullable=False),sa.Column("signal_started_at",sa.DateTime(timezone=True),nullable=False),sa.Column("detected_at",sa.DateTime(timezone=True),nullable=False),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("estimated_net_edge",sa.Float,nullable=False),sa.Column("payload",sa.JSON,nullable=False),sa.Column("is_test",sa.Boolean,nullable=False,server_default=sa.false()))
    for name,cols in (("ix_csl_signals_session_status",["match_session_id","status"]),("ix_csl_dynamic_signals_outcome",["outcome"]),("ix_csl_dynamic_signals_strategy_type",["strategy_type"]),("ix_csl_dynamic_signals_leader_venue",["leader_venue"]),("ix_csl_dynamic_signals_follower_venue",["follower_venue"]),("ix_csl_dynamic_signals_detected_at",["detected_at"]),("ix_csl_dynamic_signals_expires_at",["expires_at"]),("ix_csl_dynamic_signals_status",["status"]),("ix_csl_dynamic_signals_is_test",["is_test"]),("ix_csl_dynamic_signals_match_session_id",["match_session_id"])):op.create_index(name,"csl_dynamic_signals",cols)
    op.create_table("csl_dynamic_execution_scenarios",sa.Column("id",sa.String(260),primary_key=True),sa.Column("signal_id",sa.String(220),nullable=False),sa.Column("strategy_type",sa.String(32),nullable=False),sa.Column("latency_ms",sa.Integer,nullable=False),sa.Column("execute_at",sa.DateTime(timezone=True),nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("actual_vwap",sa.Float),sa.Column("fill_size",sa.Float,nullable=False),sa.Column("fill_ratio",sa.Float,nullable=False),sa.Column("realized_entry_edge",sa.Float),sa.Column("paper_pnl",sa.Float),sa.Column("payload",sa.JSON,nullable=False),sa.Column("is_test",sa.Boolean,nullable=False,server_default=sa.false()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("signal_id","latency_ms",name="uq_csl_signal_latency"))
    for name,cols in (("ix_csl_scenarios_signal_latency",["signal_id","latency_ms"]),("ix_csl_dynamic_execution_scenarios_strategy_type",["strategy_type"]),("ix_csl_dynamic_execution_scenarios_latency_ms",["latency_ms"]),("ix_csl_dynamic_execution_scenarios_execute_at",["execute_at"]),("ix_csl_dynamic_execution_scenarios_status",["status"]),("ix_csl_dynamic_execution_scenarios_is_test",["is_test"]),("ix_csl_dynamic_execution_scenarios_signal_id",["signal_id"])):op.create_index(name,"csl_dynamic_execution_scenarios",cols)

def downgrade():
    op.drop_table("csl_dynamic_execution_scenarios");op.drop_table("csl_dynamic_signals");op.drop_table("csl_market_price_ticks");op.drop_table("csl_match_sessions")
